import Footer from './components/Footer/Footer'
import Header from './components/header/Header'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import './components/home/home.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='vi'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
